<<<<<<< HEAD
theme: jekyll-theme-hacker
# hello this is my simple  pages , hope you like it .

## table of content 

|| topic name           	| page link  	|   	  
|what is text editor    	|[texteditor](/home/mais/102/reading-notes/TextEditor.md)	|
|   common features for text editors	|   [commonfeaturs](/home/mais/102/reading-notes/commonfeatures.md)	|   basic vs specific	| [basicVsspecific](/home/mais/102/reading-notes/basic vs specific)
|   coomand for terminal	|  [comamand] (/home/mais/102/reading-notes/command terminal)	|   
=======
theme: jekyll-theme-midnight
>>>>>>> 7b4bc218e57b8494cd4acdc8098423b04c616276
